micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/gamapicli
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages: 'com.example.domain'